### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by jvmlet** [EvidentSolutions/apina#68] opened 2021-09-19 11:56 UTC
I'm getting below error when executing with JDK `17` and gradle `7.2`:
````
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at fi.evident.apina.java.reader.ClassMetadataReader$MyMethodVisitor.visitParameter(ClassMetadataReader.kt:161)
	at fi.evident.apina.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1387)
	at fi.evident.apina.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at fi.evident.apina.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at fi.evident.apina.java.reader.ClassMetadataReader.loadMetadata(ClassMetadataReader.kt:19)
	at fi.evident.apina.java.reader.ClasspathClassDataLoader$FileClassDataLoader$data$2.invoke(ClasspathClassDataLoader.kt:128)
	at fi.evident.apina.java.reader.ClasspathClassDataLoader$FileClassDataLoader$data$2.invoke(ClasspathClassDataLoader.kt:127)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at fi.evident.apina.java.reader.ClasspathClassDataLoader$FileClassDataLoader.getData(ClasspathClassDataLoader.kt)
	at fi.evident.apina.java.reader.ClasspathClassDataLoader$FileClassDataLoader.get(ClasspathClassDataLoader.kt:130)
	at fi.evident.apina.java.reader.ClasspathClassDataLoader$FileClassDataLoader.get(ClasspathClassDataLoader.kt:127)
	at fi.evident.apina.java.reader.ClasspathClassDataLoader.loadClass(ClasspathClassDataLoader.kt:38)
	at fi.evident.apina.java.model.JavaModel.findClasses(JavaModel.kt:21)
	at fi.evident.apina.java.model.JavaModel.findClassesWithAnnotation(JavaModel.kt:24)
	at fi.evident.apina.spring.SpringModelReader.createEndpointsForControllers(SpringModelReader.kt:36)
	at fi.evident.apina.spring.SpringModelReader.access$createEndpointsForControllers(SpringModelReader.kt:29)
	at fi.evident.apina.spring.SpringModelReader$Companion.readApiDefinition(SpringModelReader.kt:146)
	at fi.evident.apina.spring.SpringModelReader$Companion.readApiDefinition(SpringModelReader.kt:165)
````

Running with jdk `13` works as expected

**Comment by komu** [comment] 2021-09-20 11:37
Which version are you using? Latest `0.17.0`?

**Comment by komu** [comment] 2021-09-20 11:52
I tested running `0.16.0` and `0.17.0` with OpenJDK 17 against quite a large codebase without any problems. Anyway, I doubt the problem is the JDK that Apina is running with, but the target JDK of the bytecode that is parsed.

Based on the exception, It seems that for never bytecode [parseMethodSignature](https://github.com/EvidentSolutions/apina/blob/2261111a938a95a097a67e9751849cc42570ac28/apina-core/src/main/kotlin/fi/evident/apina/java/reader/TypeParser.kt#L29) misparses the method signature and returns fever amount of parameters than the method actually has.

If you can provide a minimal reproducible example of code that triggers the problem, it would help a lot.

**Comment by jvmlet** [comment] 2021-09-20 12:16
> Which version are you using? Latest `0.17.0`?

Yes, `0.17.0`

Btw, with which version of Spring boot did you test `0.17.0` and  jdk `17`? You never know what they do with `bytebuddy`, I'm on `2.4.2`

**Comment by jvmlet** [comment] 2021-09-20 12:17
Will try to set the reproducible repo later this week.

**Comment by komu** [comment] 2021-09-20 12:30
I tested against Spring Boot 2.5.4, but since most of our codebase is Kotlin, I mostly ended up testing the Kotlin compiler's output, which is probably completely different from JDK 17's javac's output. I'll see if I can find a time to setup a small Java project to test against.

**Comment by jvmlet** [comment] 2021-09-22 08:21
@komu , I was able to narrow  down the root cause of the error by debugging the plugin in remote JVM debug :


![image](https://user-images.githubusercontent.com/6664858/134307868-946f896b-1c21-4e8d-873a-ec79d897a159.png)

`com.xxxxx.TestSecurityConfig$2` is the below class, if I remove it, `apina` task completes successfully :

```java
@Configuration
@EnableWebSecurity
@ConditionalOnProperty(name = "keycloak.enabled", havingValue = "false")
public class TestSecurityConfig extends WebSecurityConfigurerAdapter {
   // ..... more config classes
    @Bean
    public WebMvcConfigurer corsConfigurer(@Value("${allowedOrigins:http://localhost:4201}") String allowedOrigins) {
        return new WebMvcConfigurer() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry
                        .addMapping("/**")
                        .allowedMethods(Stream.of(HttpMethod.values())
                                .map(HttpMethod::name)
                                .toArray(String[]::new)
                        )
                        .allowedOrigins(allowedOrigins.split(","));
            }
        };
    }
}
```

**Comment by komu** [comment] 2021-09-22 08:31
Thanks, I'll try to reproduce based on that.

But I have an immediate workaround that will also make your Apina processor faster. Try specifying setting Apina's `endpoints`-property to a regex that matches only the class names of your controllers:

```kotlin
tasks.apina {
    // Regex matching our controller classes
    endpoints = listOf("""my\.project\.api\..+""")
}
```

There's no harm if the regex matches too much, but it will speed up Apina a lot because it doesn't have to parse all the bytecode in your project: it will first only load the classes that match any of the given regexes, look for `@RestController`-annotations in those and then it will load the classes that are referenced by our controllers. If you don't specify any regexes, then Apina will load all classes trying to find the annotations.

So not only your build will be faster, you'll avoid loading the problematic configuration class.

**Comment by jvmlet** [comment] 2021-09-22 09:16
Thanks, I'm actually using 

```gradle
tasks.apina {
    platform = 'angular'
    endpoints = [/com\.xxx\..+/]
}
```
After changing  it to  `endpoints = [/com\.xxx\.(?!.*TestSecurityConfig).+/]` I got my proxies generated.

**Comment by alexey-anufriev** [comment] 2022-03-22 01:11
@komu, from what I see Java 17 `record`s are not supported. Are there any plans?

**Comment by komu** [comment] 2022-03-24 20:14
I just pushed https://github.com/EvidentSolutions/apina/pull/71 to support records.

I'm also trying to reproduce this, but I can't reproduce. @jvmlet Any change you could try to simplify the code to make a minimal failing `.java` file without any third party dependencies? And perhaps pass the `.class` file as well?

**Comment by jvmlet** [comment] 2022-03-25 05:35
Sorry @komu, but I don't have the access to the environment where I could reproduce the issue anymore

**Comment by komu** [comment] 2022-03-25 06:16
Okay, no problem.

Anyway, since Apina should support Java 17 and I've upgraded ASM in the meantime perhaps the issue has gone away. I'll close this issue and trust that someone will open another if the problem persists.

**Closed as completed** 2022-03-25 06:16 UTC

**Comment by jvmlet** [comment] 2022-03-25 07:58
Thanks @komu. Apina is a great tool that dramatically simplifies rpc. I really enjoyed the simplicity and powerfulnes of  generated client.
